### ISSUE TITLE
Add the role to every playbook (in config files)

### ISSUE THREAD

**Issue by BarbzYHOOL** [andrewvaughan/ansible-prompt#80]
Is it possible to add the role to a configuration file (either for inventory or for all in /etc/) so that it's usable on every playbooks by default?

**Comment by andrewvaughan** [comment]
Hey @BarbzYHOOL, thanks for the request.  I'm not certain I fully understand it, however.  Can you provide an example of what you mean?

**Comment by BarbzYHOOL** [comment]
In ansible.cfg:

    av.role-prompt: yes

And then on all playbooks I can forget about adding "role: ansible-role-prompt" before using the actual prompt

If not clear, tell me again

**Comment by andrewvaughan** [comment]
This is a feature you would need to request from the main Ansible repository.

**Comment by BarbzYHOOL** [comment]
Ok :'( (but I won't because it's useless to open any issue there)
